name: CI

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Release and publish
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.16
          cache: pnpm

      # - name: Setup Rust build
      #   run: npm run r-install

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release